Import('env')

env.InstallFrontend(['layout.html', 'index.html', 'help.html',
                     'contact.html', 'submit.html', 'results_ok.html',
                     'results_failed.html', 'download.html'], 'templates')
